language: node_js
node_js:
- '6'

services:
  - elasticsearch
  - redis-server

before_script:
  - sleep 15

script: ./scripts/install.sh && ./scripts/run.sh

env:
  KUZZLE_REPO: kuzzleio/kuzzle
  KUZZLE_VERSION: master
  KUZZLE_VERSION: 1.0.0-RC8.1
  KUZZLE_KEEP_DEFAULT_PLUGIN: true
  KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master

  PROXY_REPO: kuzzleio/kuzzle-proxy
  PROXY_VERSION: master
  PROXY_VERSION: 1.0.0-RC9
  PROXY_VERSION: 1.0.0-RC8
  PROXY_KEEP_DEFAULT_PLUGIN: true
  PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
