services:
  - elasticsearch
  - redis-server

before_script:
  - sleep 15

before_install: ./scripts/pre-install.sh
install: travis_retry ./scripts/install.sh
script: ./scripts/run.sh

os: linux
sudo: required

env:
  - KUZZLE_REPO: kuzzleio/kuzzle
    KUZZLE_VERSION: master
    KUZZLE_KEEP_DEFAULT_PLUGIN: true
    KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
    PROXY_REPO: kuzzleio/kuzzle-proxy
    PROXY_VERSION: master
    PROXY_KEEP_DEFAULT_PLUGIN: true
    PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
    NODE_VERSION: 6.9.5
    GLOBAL_PM2_VERSION: 2.0.19
    GIT_SSL_NO_VERIFY: true
  - KUZZLE_REPO: kuzzleio/kuzzle
    KUZZLE_VERSION: 1.0.0-RC9
    KUZZLE_KEEP_DEFAULT_PLUGIN: true
    KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    PROXY_REPO: kuzzleio/kuzzle-proxy
    PROXY_VERSION: 1.0.0-RC9
    PROXY_KEEP_DEFAULT_PLUGIN: true
    PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    NODE_VERSION: 6.9.5
    GLOBAL_PM2_VERSION: 2.0.19
    GIT_SSL_NO_VERIFY: true
  - KUZZLE_REPO: kuzzleio/kuzzle
    KUZZLE_VERSION: 1.0.0-RC8.1
    KUZZLE_KEEP_DEFAULT_PLUGIN: true
    KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    PROXY_REPO: kuzzleio/kuzzle-proxy
    PROXY_VERSION: 1.0.0-RC8
    PROXY_KEEP_DEFAULT_PLUGIN: true
    PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    NODE_VERSION: 6.9.5
    GLOBAL_PM2_VERSION: 2.0.19
    GIT_SSL_NO_VERIFY: true
