before_install: sudo ./scripts/prepare-system.sh

script: sudo ./scripts/install-sandbox.sh && sudo ./scripts/run-tests.sh
after_script: sudo ./scripts/upload-matrix.sh

after_failure: sudo ./scripts/dump-errors.sh

os: linux
sudo: required
dist: trusty
language: generic

matrix:
  fast_finish: true
  allow_failures:
    # nightly open source version
    - env: KUZZLE_REPO=kuzzleio/kuzzle KUZZLE_VERSION=rc.x KUZZLE_COMMON_OBJECT_VERSION=kuzzleio/kuzzle-common-objects@2.x KUZZLE_PLUGINS=kuzzleio/kuzzle-plugin-auth-passport-oauth@3.x:kuzzleio/kuzzle-plugin-auth-passport-local@4.x:kuzzleio/kuzzle-plugin-logger@2.x BACKOFFICE_REPO=kuzzleio/kuzzle-backoffice BACKOFFICE_VERSION=2.x PROXY_REPO=kuzzleio/kuzzle-proxy PROXY_VERSION=rc.x PROXY_COMMON_OBJECT_VERSION=kuzzleio/kuzzle-common-objects@2.x PROXY_PLUGINS=kuzzleio/kuzzle-plugin-mqtt@2.x



env:
  global:
    - NODE_VERSION: 6.9.5
    - GLOBAL_PM2_VERSION: 2.0.19
    - GCC_VERSION: 4.9
    - ES_VERSION: 5.1
    - REDIS_VERSION: 3.2
    - NODE_ENV: "development"
    - DEBUG: "kuzzle*"
  matrix:
     # RC9.6 open source version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9.6
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC9
      BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
      BACKOFFICE_VERSION: 2.x
    # latest open source version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: master
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-oauth@3.x:kuzzleio/kuzzle-plugin-auth-passport-local@3.x:kuzzleio/kuzzle-plugin-logger@2.x
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: master
      PROXY_PLUGINS: kuzzleio/kuzzle-plugin-mqtt@2.x
      BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
      BACKOFFICE_VERSION: 2.x
    # RC9.6 entreprise version (round-robin)
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9.6
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-oauth@3.x:kuzzleio/kuzzle-plugin-auth-passport-local@3.x:kuzzleio/kuzzle-plugin-logger@2.x:kuzzleio/kuzzle-plugin-cluster@1.x
      PROXY_REPO: kuzzleio/kuzzle-load-balancer
      PROXY_VERSION: 1.x
      BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
      BACKOFFICE_VERSION: 2.x
      LB_PROXY_VERSION: kuzzleio/kuzzle-proxy@1.0.0-RC9
      "proxy_backend__mode": round-robin
      "kuzzle_plugins__kuzzle-plugin-cluster__privileged": true
      "kuzzle_services__internalBroker__socket": false
      "kuzzle_services__internalBroker__host": 0.0.0.0
      "kuzzle_services__internalBroker__port": 7911
    # RC9.6 entreprise version (failover)
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9.6
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-oauth@3.x:kuzzleio/kuzzle-plugin-auth-passport-local@3.x:kuzzleio/kuzzle-plugin-logger@2.x:kuzzleio/kuzzle-plugin-cluster@1.x
      PROXY_REPO: kuzzleio/kuzzle-load-balancer
      PROXY_VERSION: 1.x
      BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
      BACKOFFICE_VERSION: 2.x
      LB_PROXY_VERSION: kuzzleio/kuzzle-proxy@1.0.0-RC9
      "proxy_backend__mode": failover
      "kuzzle_plugins__kuzzle-plugin-cluster__privileged": true
      "kuzzle_services__internalBroker__socket": false
      "kuzzle_services__internalBroker__host": 0.0.0.0
      "kuzzle_services__internalBroker__port": 7911
    # nightly open source version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: rc.x
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects@2.x
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-oauth@3.x:kuzzleio/kuzzle-plugin-auth-passport-local@4.x:kuzzleio/kuzzle-plugin-logger@2.x
      BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
      BACKOFFICE_VERSION: 2.x
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: rc.x
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects@2.x
      PROXY_PLUGINS: kuzzleio/kuzzle-plugin-mqtt@2.x
