language: node_js
node_js:
- '6'

addons:
  apt:
    packages:
      - build-essential
      - curl
      - git
      - g++
      - gdb
      - python

services:
  - elasticsearch
  - redis-server

before_script:
  - sleep 15

script: travis_retry ./scripts/install.sh && ./scripts/run.sh

os: linux

matrix:
  include:
  - dist: trusty
    env:
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: master
      KUZZLE_KEEP_DEFAULT_PLUGIN: true
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: master
      PROXY_KEEP_DEFAULT_PLUGIN: true
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9
      KUZZLE_KEEP_DEFAULT_PLUGIN: true
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC9
      PROXY_KEEP_DEFAULT_PLUGIN: true
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC8.1
      KUZZLE_KEEP_DEFAULT_PLUGIN: true
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC8
      PROXY_KEEP_DEFAULT_PLUGIN: true
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
  - dist: precise
    env:
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: master
      KUZZLE_KEEP_DEFAULT_PLUGIN: true
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: master
      PROXY_KEEP_DEFAULT_PLUGIN: true
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9
      KUZZLE_KEEP_DEFAULT_PLUGIN: true
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC9
      PROXY_KEEP_DEFAULT_PLUGIN: true
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC8.1
      KUZZLE_KEEP_DEFAULT_PLUGIN: true
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC8
      PROXY_KEEP_DEFAULT_PLUGIN: true
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
  
