before_install: sudo ./scripts/prepare-system.sh

script: sudo ./scripts/install-sandbox.sh && sudo ./scripts/run-tests.sh
after_script: sudo ./scripts/upload-matrix.sh

after_failure: sudo ./scripts/dump-errors.sh

os: linux
sudo: required
dist: trusty
language: generic

matrix:
  fast_finish: true
  allow_failures:
    # nightly open source version
    - env: KUZZLE_VERSION=1.x PROXY_VERSION=1.x BACKOFFICE_VERSION=2.x
    # nightly entreprise version
    - env: KUZZLE_VERSION=1.x KUZZLE_PLUGINS=kuzzleio/kuzzle-plugin-auth-passport-oauth@4.x:kuzzleio/kuzzle-plugin-auth-passport-local@5.x:kuzzleio/kuzzle-plugin-logger@2.x:kuzzleio/kuzzle-plugin-cluster@1.x KUZZLE_EXTRA_ENV=kuzzle_plugins__kuzzle-plugin-cluster__privileged=true kuzzle_services__internalBroker__socket=false kuzzle_services__internalBroker__host=0.0.0.0 kuzzle_services__internalBroker__port=7911 PROXY_REPO=kuzzleio/kuzzle-load-balancer PROXY_VERSION=1.x PROXY_PLUGINS=kuzzleio/kuzzle-plugin-mqtt@2.x PROXY_EXTRA_ENV=proxy_backend__mode=round-robin LB_PROXY_VERSION=kuzzleio/kuzzle-proxy@1.x BACKOFFICE_VERSION=2.x


env:
  global:
    - NODE_VERSION: "6.11.0"
    - GLOBAL_PM2_VERSION: "2.5.0"
    - GCC_VERSION: "4.9"
    - ES_VERSION: "5.4.1"
    - REDIS_VERSION: "3.2.9"
    - NODE_ENV: "development"
    - DEBUG: "kuzzle*"
    # default values
    - KUZZLE_REPO: kuzzleio/kuzzle
    - KUZZLE_VERSION: master
    - PROXY_REPO: kuzzleio/kuzzle-proxy
    - PROXY_VERSION: master
    - BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
    - BACKOFFICE_VERSION: master
  matrix:
    # 1.0.0 open source version
    - KUZZLE_VERSION: 1.0.0
      PROXY_VERSION: 1.0.0
      BACKOFFICE_VERSION: 2.1.0
    # 1.0.0 entreprise version (round-robin)
    - KUZZLE_VERSION: 1.0.0
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-oauth@4.x:kuzzleio/kuzzle-plugin-auth-passport-local@5.0.0:kuzzleio/kuzzle-plugin-logger@2.0.8:kuzzleio/kuzzle-plugin-cluster@1.x
      KUZZLE_EXTRA_ENV: "kuzzle_plugins__kuzzle-plugin-cluster__privileged=true kuzzle_services__internalBroker__socket=false kuzzle_services__internalBroker__host=0.0.0.0 kuzzle_services__internalBroker__port=7911"
      PROXY_REPO: kuzzleio/kuzzle-load-balancer
      PROXY_VERSION: 1.x
      PROXY_EXTRA_ENV: "proxy_backend__mode=round-robin"
      LB_PROXY_VERSION: kuzzleio/kuzzle-proxy@1.0.0
      BACKOFFICE_VERSION: 2.1.0
    # nightly open source version
    - KUZZLE_VERSION: 1.x
      PROXY_VERSION: 1.x
      BACKOFFICE_VERSION: 2.x
    # nightly entreprise version
    - KUZZLE_VERSION: 1.x
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-oauth@4.x:kuzzleio/kuzzle-plugin-auth-passport-local@5.x:kuzzleio/kuzzle-plugin-logger@2.x:kuzzleio/kuzzle-plugin-cluster@1.x
      KUZZLE_EXTRA_ENV: "kuzzle_plugins__kuzzle-plugin-cluster__privileged=true kuzzle_services__internalBroker__socket=false kuzzle_services__internalBroker__host=0.0.0.0 kuzzle_services__internalBroker__port=7911"
      PROXY_REPO: kuzzleio/kuzzle-load-balancer
      PROXY_VERSION: 1.x
      PROXY_PLUGINS: kuzzleio/kuzzle-plugin-mqtt@2.x
      PROXY_EXTRA_ENV: proxy_backend__mode=round-robin
      LB_PROXY_VERSION: kuzzleio/kuzzle-proxy@1.x
      BACKOFFICE_VERSION: 2.x
