services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install: sudo ./scripts/pre-install.sh
install: travis_retry ./scripts/install.sh

script: ./scripts/run.sh
os: linux
sudo: required

env:
  - KUZZLE_REPO: kuzzleio/kuzzle
    KUZZLE_VERSION: master
    KUZZLE_KEEP_DEFAULT_PLUGIN: true
    KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
    PROXY_REPO: kuzzleio/kuzzle-proxy
    PROXY_VERSION: master
    PROXY_KEEP_DEFAULT_PLUGIN: true
    PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
    NODE_VERSION: 6.9.5
    GLOBAL_PM2_VERSION: 2.0.19
    GIT_SSL_NO_VERIFY: true
    GCC_VERSION: 4.9
    ES_VERSION: 5
    REDIS_VERSION: 3
  - KUZZLE_REPO: kuzzleio/kuzzle
    KUZZLE_VERSION: 1.0.0-RC9
    KUZZLE_KEEP_DEFAULT_PLUGIN: true
    KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    PROXY_REPO: kuzzleio/kuzzle-proxy
    PROXY_VERSION: 1.0.0-RC9
    PROXY_KEEP_DEFAULT_PLUGIN: true
    PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.1.2
    NODE_VERSION: 6.9.5
    GLOBAL_PM2_VERSION: 2.0.19
    GIT_SSL_NO_VERIFY: true
    GCC_VERSION: 4.9
    ES_VERSION: 5
    REDIS_VERSION: 3
  - KUZZLE_REPO: kuzzleio/kuzzle
    KUZZLE_VERSION: rc.x
    KUZZLE_KEEP_DEFAULT_PLUGIN: true
    KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.x
    PROXY_REPO: kuzzleio/kuzzle-proxy
    PROXY_VERSION: rc.x
    PROXY_KEEP_DEFAULT_PLUGIN: true
    PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#2.x
    NODE_VERSION: 6.9.5
    GLOBAL_PM2_VERSION: 2.0.19
    GIT_SSL_NO_VERIFY: true
    GCC_VERSION: 4.9
    ES_VERSION: 5
    REDIS_VERSION: 3
