services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install: sudo ./scripts/pre-install.sh
install: travis_retry ./scripts/install.sh

script: ./scripts/run.sh
after_success: ./scripts/success.sh
after_failure: "echo KO"
after_script: "echo ENDED"

os: linux
sudo: required

env:
  global:
    - NODE_VERSION: 6.9.5
    - GLOBAL_PM2_VERSION: 2.0.19
    - GCC_VERSION: 4.9
    - ES_VERSION: 5
    - REDIS_VERSION: 3
  matrix:
    # RC9 version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC9
    # RC9.1 version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9.1
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC9
    # RC9.2 version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9.2
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC9
    # RC9.2 entreprise version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: 1.0.0-RC9.2
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-local#3.0.4:kuzzleio/kuzzle-plugin-logger#3.0.0:kuzzleio/kuzzle-plugin-cluster#1.0.0
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: 1.0.0-RC9
      PROXY_PLUGINS: kuzzleio/kuzzle-plugin-mqtt#2.0.1
      "kuzzle_plugins__kuzzle-plugin-cluster__privileged": true
    # latest version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: master
      KUZZLE_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
      KUZZLE_PLUGINS: kuzzleio/kuzzle-plugin-auth-passport-oauth:kuzzleio/kuzzle-plugin-auth-passport-local:kuzzleio/kuzzle-plugin-logger
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: master
      PROXY_COMMON_OBJECT_VERSION: kuzzleio/kuzzle-common-objects#master
