before_install: sudo ./scripts/prepare-system.sh

script: sudo ./scripts/install-sandbox.sh && sudo ./scripts/run-tests.sh
after_script: sudo ./scripts/upload-matrix.sh

after_failure: sudo ./scripts/dump-errors.sh

os: linux
sudo: required
dist: trusty
language: generic

env:
  global:
    - NODE_VERSION: 6.9.5
    - GLOBAL_PM2_VERSION: 2.0.19
    - GCC_VERSION: 4.9
    - ES_VERSION: 5.1
    - REDIS_VERSION: 3.2
    - NODE_ENV: "development"
    - DEBUG: "kuzzle*"
  matrix:
     # RC9.6 open source version
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: graceful-shutdown
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: rc.x
      BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
      BACKOFFICE_VERSION: 2.x
    - KUZZLE_REPO: kuzzleio/kuzzle
      KUZZLE_VERSION: graceful-shutdown
      PROXY_REPO: kuzzleio/kuzzle-proxy
      PROXY_VERSION: rc.x
      BACKOFFICE_REPO: kuzzleio/kuzzle-backoffice
      BACKOFFICE_VERSION: 2.x
      NODE_ENV: production
