version: '2'

services:
  sandbox:
    image: debian:jessie
    command: /bin/bash -c '/scripts/pre-install.sh && /scripts/install.sh && /scripts/run.sh'
    env_file:
      - ./common.env
    volumes:
      - "./scripts:/scripts"
    depends_on:
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis

  redis:
    image: redis:3
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:5
    ports:
      - 9200:9200
