version: '2'

services:
  sandbox:
    image: debian:jessie
    command: /bin/bash -c '/scripts/pre-install.sh && /scripts/install.sh && /scripts/run.sh'
    env_file:
      - ./common.env
      - ./private.env
    volumes:
      - "./scripts:/scripts"
      # - "./cache/npm:/root/.npm"
      # - "./cache/docker:/var/lib/docker/image"
      # - "./cache/apt:/var/cache/apt/archives/"
    ports:
      - 7331:7331
    privileged: true
    environment:
      - kuzzle_services__db__host=localhost
      - kuzzle_services__internalCache__node__host=localhost
      - kuzzle_services__memoryStorage__node__host=localhost
      - proxy_backend__mode=round-robin
      - kuzzle_plugins__kuzzle-plugin-cluster__privileged=true
