version: '2'

services:
  sandbox:
    image: debian:jessie
    command: /bin/bash -c '/scripts/pre-install.sh && /scripts/install.sh && /scripts/run.sh'
    env_file:
      - ./env/common.env
      - ./env/private.env
    volumes:
      - "./scripts:/scripts"
      - "./config/kuzzlerc:/etc/kuzzlerc"
      - "./config/proxyrc:/etc/proxyrc"
      # - "./cache/npm:/root/.npm"
      # - "./cache/docker:/var/lib/docker/image"
      # - "./cache/apt:/var/cache/apt/archives/"
    ports:
      - 7331:7331
    privileged: true
